source 'https://rubygems.org'

gem 'telegram-bot-ruby'
gem 'prawn'
gem 'prawn-table'
gem 'pg'
gem 'activerecord'
gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'nokogiri', '~> 1.16.6'
gem 'mini_portile2', '~> 2.8.2'
